### ISSUE TITLE
Process input files

### ISSUE THREAD

**Issue by ssathya** [ssathya/IMDBMongo#2]
Uncompressed the files and convert them into JSON files.
This is a multi-step process. 
- [x] Unzip the files

Each file has got its own format. Need to handle each file case by case.
- [x] mpaa-ratings-reasons.list.gz
- [x] crazy-credits.list.gz
- [x] alternate-versions.list.gz
- [x] costume-designers.list.gz
- [x] certificates.list.gz
- [x] taglines.list.gz
- [x] production-designers.list.gz
- [x] literature.list.gz
- [x] sound-mix.list.gz
- [x] business.list.gz
- [x] ratings.list.gz
- [x] locations.list.gz
- [ ] running-times.list.gz
- [ ] miscellaneous-companies.list.gz
- [ ] composers.list.gz
- [ ] genres.list.gz
- [ ] color-info.list.gz
- [ ] countries.list.gz
- [ ] language.list.gz
- [ ] cinematographers.list.gz
- [ ] soundtracks.list.gz
- [ ] goofs.list.gz
- [ ] editors.list.gz
- [ ] directors.list.gz
- [ ] movies.list.gz
- [ ] keywords.list.gz
- [ ] trivia.list.gz
- [ ] release-dates.list.gz
- [ ] quotes.list.gz
- [ ] producers.list.gz
- [ ] miscellaneous.list.gz
- [ ] plot.list.gz
- [ ] actresses.list.gz
- [ ] biographies.list.gz
- [ ] actors.list.gz

**Comment by YouthLab** [comment]
Hi, Sridhar.
My name is Youth Tsui.  I am a developer come from china. If you want, i think we can work together to finish this project.
Tsui@HighYouth.COM

**Comment by ssathya** [comment]
Why would one refuse help?😊👍
Will send you details about the project plan in 12 to 24 hours. 

By the way do you have access to visual Studio online? I maintain source code and ALM there and mirror my code at github.com.

**Comment by YouthLab** [comment]
@ssathya Great! I am glad you invited me to join. I did have a Microsoft account: tsui@highyouth.com, and also i have an account on TFS Online. Hope for your reply soon, by the way i have not have your email address yet ：）.
